[[redirects]]
  from = "/api:splat"
  to = "https://api.privatbank.ua/p24api/pubinfo?json&exchange&coursid=5"
  status = 200
  force = true
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"